### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by aashish108** [luhmann/evernote-to-raindrop-exporter#1]
Hey! I get this error so its not working; I did do `npm i` at the start:

```
PS E:\Projects\Dev\evernote-to-raindrop-exporter> node -v
v14.15.0
PS E:\Projects\Dev\evernote-to-raindrop-exporter> npm start

> evernote-to-raindrop-exporter@2.0.0 start E:\Projects\Dev\evernote-to-raindrop-exporter
> ts-node --project 'tsconfig.json' src/index.ts


E:\Projects\Dev\evernote-to-raindrop-exporter\node_modules\ts-node\src\index.ts:513
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
error TS5083: Cannot read file 'E:\Projects\Dev\evernote-to-raindrop-exporter\'tsconfig.json''.

    at createTSError (E:\Projects\Dev\evernote-to-raindrop-exporter\node_modules\ts-node\src\index.ts:513:12)
    at reportTSError (E:\Projects\Dev\evernote-to-raindrop-exporter\node_modules\ts-node\src\index.ts:517:19)
    at create (E:\Projects\Dev\evernote-to-raindrop-exporter\node_modules\ts-node\src\index.ts:528:36)
    at Object.register (E:\Projects\Dev\evernote-to-raindrop-exporter\node_modules\ts-node\src\index.ts:410:19)
    at main (E:\Projects\Dev\evernote-to-raindrop-exporter\node_modules\ts-node\src\bin.ts:151:19)
    at Object.<anonymous> (E:\Projects\Dev\evernote-to-raindrop-exporter\node_modules\ts-node\src\bin.ts:288:3)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
```

**Comment by aashish108** [comment]
OK its working on my Ubuntu (Via WSL). So its just a Windows thing!

**Comment by luhmann** [comment]
Thank you for the feedback!

I could only really test it on macOS as I do not own a Windows license.

> Cannot read file 'E:\Projects\Dev\evernote-to-raindrop-exporter\'tsconfig.json''

Judging purely from that output I would guess that it is an issue with the quotes around `tsconfig.json` in the `npm start`-command but without a way to test it I cannot be sure.

But if you could get it to work by using WSL, that feels like a feasible way of using the script also on Windows to me. I added a comment for that to README based on your experience.
